version: '3.8'

services:
  photo-organizer-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photo-organizer-dev
    volumes:
      - ../:/workspaces/photo-org:cached
      - photo-organizer-node-modules:/workspaces/photo-org/node_modules
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - TERM=xterm-256color
    working_dir: /workspaces/photo-org
    command: tail -f /dev/null
    user: node
    stdin_open: true
    tty: true

volumes:
  photo-organizer-node-modules:
